"""empty message

Revision ID: 156ba8d1ae00
Revises: 460c1ab530a3
Create Date: 2019-09-10 23:49:01.705236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '156ba8d1ae00'
down_revision = '460c1ab530a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('screen_name', sa.String(length=100), nullable=False))
    op.drop_index('address', table_name='user')
    op.drop_index('phone', table_name='user')
    op.create_unique_constraint(None, 'user', ['password'])
    op.create_unique_constraint(None, 'user', ['screen_name'])
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('user', sa.Column('address', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('phone', 'user', ['phone'], unique=True)
    op.create_index('address', 'user', ['address'], unique=True)
    op.drop_column('user', 'screen_name')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
