"""empty message

Revision ID: 59dc405638ca
Revises: 156ba8d1ae00
Create Date: 2019-09-11 23:05:43.225375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59dc405638ca'
down_revision = '156ba8d1ae00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('team_id', sa.String(length=120), nullable=False),
    sa.Column('computer_team_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('computer_team_id'),
    sa.UniqueConstraint('team_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=80), nullable=False),
    sa.Column('attack', sa.String(length=80), nullable=False),
    sa.Column('defense', sa.String(length=80), nullable=False),
    sa.Column('player_id', sa.String(length=120), nullable=False),
    sa.Column('team_goals', sa.String(length=100), nullable=False),
    sa.Column('team_passes', sa.String(length=120), nullable=False),
    sa.Column('team_fouls', sa.String(length=120), nullable=False),
    sa.Column('team_blocked_shots', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attack'),
    sa.UniqueConstraint('defense'),
    sa.UniqueConstraint('player_id'),
    sa.UniqueConstraint('team_blocked_shots'),
    sa.UniqueConstraint('team_fouls'),
    sa.UniqueConstraint('team_goals'),
    sa.UniqueConstraint('team_id'),
    sa.UniqueConstraint('team_passes')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('team_id', sa.String(length=120), nullable=False),
    sa.Column('fixture_id', sa.String(length=120), nullable=False),
    sa.Column('activity_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id'),
    sa.UniqueConstraint('fixture_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('player')
    op.drop_table('game')
    op.drop_table('activity')
    # ### end Alembic commands ###
