"""empty message

Revision ID: 78d6b422f704
Revises: 87940a464f2f
Create Date: 2019-09-18 23:40:48.696646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d6b422f704'
down_revision = '87940a464f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'player', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_column('player', 'team_id')
    # ### end Alembic commands ###
