"""empty message

Revision ID: 87940a464f2f
Revises: ee830be236c4
Create Date: 2019-09-18 23:20:14.121756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87940a464f2f'
down_revision = 'ee830be236c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_ibfk_1', 'player', type_='foreignkey')
    op.drop_column('player', 'teamId')
    op.add_column('teams', sa.Column('team_id', sa.String(length=120), nullable=False))
    op.drop_index('teamId', table_name='teams')
    op.create_unique_constraint(None, 'teams', ['team_id'])
    op.drop_column('teams', 'teamId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('teamId', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'teams', type_='unique')
    op.create_index('teamId', 'teams', ['teamId'], unique=True)
    op.drop_column('teams', 'team_id')
    op.add_column('player', sa.Column('teamId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('player_ibfk_1', 'player', 'teams', ['teamId'], ['id'])
    # ### end Alembic commands ###
