"""empty message

Revision ID: e98419ea84f9
Revises: 78d6b422f704
Create Date: 2019-09-19 22:47:54.357120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98419ea84f9'
down_revision = '78d6b422f704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('full_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('full_name', 'user', ['full_name'], unique=True)
    # ### end Alembic commands ###
