"""empty message

Revision ID: ee830be236c4
Revises: 
Create Date: 2019-09-18 00:07:56.545628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee830be236c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('team_id', sa.String(length=120), nullable=False),
    sa.Column('computer_team_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('computer_team_id'),
    sa.UniqueConstraint('team_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('teamId', sa.String(length=120), nullable=False),
    sa.Column('teamLogo', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('teamId'),
    sa.UniqueConstraint('teamLogo')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('screen_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('screen_name')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('attack', sa.String(length=80), nullable=False),
    sa.Column('defense', sa.String(length=80), nullable=False),
    sa.Column('player_id', sa.String(length=120), nullable=False),
    sa.Column('season', sa.String(length=80), nullable=False),
    sa.Column('goals_total', sa.String(length=100), nullable=False),
    sa.Column('goals_conceded', sa.String(length=100), nullable=False),
    sa.Column('passes_total', sa.String(length=120), nullable=False),
    sa.Column('tackles_total', sa.String(length=120), nullable=False),
    sa.Column('shots_total', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('user')
    op.drop_table('teams')
    op.drop_table('game')
    op.drop_table('activity')
    # ### end Alembic commands ###
